Repository PennyLaneAI/catalyst, pull requests merged in 2024-10, with the labels that each got.

#1164 Seed samples for `lightning.qubit/kokkos`
  .dep-versions
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/scripts/linux_arm64/rh8/build_catalyst.sh
  doc/releases/changelog-dev.md
  doc/requirements.txt
  frontend/test/pytest/test_measurement_transforms.py
  frontend/test/pytest/test_seeded_qjit.py
  runtime/Makefile
  runtime/lib/backend/lightning/lightning_dynamic/LightningSimulator.cpp
  runtime/tests/Test_SVDynamicCPU_Allocation.cpp
  runtime/tests/Test_SVDynamicCPU_Core.cpp
Labels: author:build-wheels, urgent

#1183 Seed CI
  frontend/test/pytest/test_mid_circuit_measurement.py
Labels: seed-CI

#1182 Change NumPy requirement to `numpy!=2.0.0`
  .dep-versions
  doc/releases/changelog-dev.md
  doc/requirements.txt
  pyproject.toml
  requirements.txt
  setup.py
Labels: author:build-wheels

#1190 Fix autograph not transforming wrapped functions in Catalyst callables
  frontend/catalyst/api_extensions/callbacks.py
  frontend/catalyst/api_extensions/differentiation.py
  frontend/catalyst/api_extensions/error_mitigation.py
  frontend/catalyst/api_extensions/function_maps.py
  frontend/catalyst/autograph/ag_primitives.py
  frontend/catalyst/jax_primitives.py
  frontend/catalyst/jit.py
  frontend/catalyst/tracing/type_signatures.py
  frontend/catalyst/utils/callables.py
  frontend/test/lit/test_autograph_integration.py
  frontend/test/lit/test_mitigation.py
  frontend/test/pytest/test_callback.py
  frontend/test/pytest/test_contexts.py
  frontend/test/pytest/test_gradient.py
  frontend/test/pytest/test_mitigation.py
  frontend/test/pytest/test_vmap.py
  pyproject.toml
Labels: bug, frontend

#1201 pin to ubuntu-22.04
  .github/workflows/build-enzyme-v0.0.130.yaml
  .github/workflows/build-nightly-release.yaml
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/changelog-reminder.yaml
  .github/workflows/check-catalyst.yaml
  .github/workflows/check-for-wheel-build.yml
  .github/workflows/check-formatting.yaml
  .github/workflows/check-jax-release.yaml
  .github/workflows/check-pl-compat.yaml
  .github/workflows/determine-workflow-runner.yml
  .github/workflows/notify-failed-jobs.yaml
  .github/workflows/rc_sync.yaml
Labels: urgent

#1200 Seed non-deterministic TestMeasurementTransforms test
  frontend/test/pytest/test_measurement_transforms.py
Labels: seed-CI

#1179 Add null qubit
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/check-catalyst.yaml
  .github/workflows/scripts/linux_arm64/rh8/build_catalyst.sh
  .gitignore
  Makefile
  doc/dev/custom_devices.rst
  frontend/catalyst/device/qjit_device.py
  frontend/test/conftest.py
  frontend/test/custom_device/custom_device.toml
  frontend/test/lit/test_decomposition.py
  frontend/test/lit/test_device_api.py
  frontend/test/pytest/conftest.py
  frontend/test/pytest/device/test_decomposition.py
  frontend/test/pytest/test_config_functions.py
  frontend/test/pytest/test_custom_devices.py
  frontend/test/pytest/test_device_api.py
  frontend/test/pytest/test_measurement_transforms.py
  frontend/test/pytest/test_preprocess.py
  runtime/CMakeLists.txt
  runtime/Makefile
  runtime/lib/backend/CMakeLists.txt
  runtime/lib/backend/dummy/CMakeLists.txt
  runtime/lib/backend/dummy/dummy_device.cpp
  runtime/lib/backend/null_qubit/.gitignore
  runtime/lib/backend/null_qubit/CMakeLists.txt
  runtime/lib/backend/null_qubit/NullQubit.cpp
  runtime/lib/backend/null_qubit/NullQubit.hpp
  runtime/lib/backend/null_qubit/null_qubit.toml
  runtime/lib/capi/ExecutionContext.hpp
  runtime/tests/CMakeLists.txt
  runtime/tests/TestUtils.hpp
  runtime/tests/Test_DLManager.cpp
  runtime/tests/Test_NullQubit.cpp
Labels: reviewer:require-wheels, author:build-wheels

#1212 Enable Autograph on qml functions
  doc/releases/changelog-dev.md
  frontend/catalyst/autograph/ag_primitives.py
  frontend/test/pytest/test_autograph.py
Labels: bug, frontend

#1221 Add '.cache' to gitignore
  .gitignore
Labels: urgent

#1223 _probs_def_impl was wrongly decorated with @var_p.def_impl
  frontend/catalyst/jax_primitives.py
Labels: frontend

#1213 Fix extrapolation in ZNE function
  doc/releases/changelog-dev.md
  frontend/catalyst/api_extensions/error_mitigation.py
  frontend/catalyst/jax_primitives.py
  frontend/test/lit/test_mitigation.py
Labels: bug, frontend

#1230 Seed pytest `test_measurement_from_samples_with_sample_measurement`
  frontend/test/pytest/test_measurement_transforms.py
Labels: seed-CI

#1233 Bump CPL RC versions for Catalyst 0.9.0
  .github/workflows/check-pl-compat.yaml
Labels: urgent

#1235 Prepare for Catalyst v0.10.0-dev (development release)
  .github/workflows/rc_sync.yaml
  doc/dev/release_notes.rst
  doc/releases/changelog-dev.md
  frontend/catalyst/_version.py
Labels: urgent

#1245 Fix a missed branch update in rcrcrc action (v0.9.0) (rc)
  .github/workflows/check-pl-compat.yaml
Labels: urgent

#1243 Fix a missed branch update in rcrcrc action (v0.9.0) (main)
  .github/workflows/check-pl-compat.yaml
Labels: urgent

#1252 Seed a flaky test in CI
  frontend/test/pytest/test_measurement_transforms.py
Labels: seed-CI

#1255 Fix MLIR default pipeline
  doc/releases/changelog-0.9.0.md
  mlir/lib/Driver/CompilerDriver.cpp
  mlir/lib/Driver/Pipelines.cpp
  mlir/test/CMakeLists.txt
  mlir/test/cli/DumpPipeline.mlir
Labels: urgent

#1238 Polish the Catalyst 0.9.0 Changelog and Documentation
  doc/dev/autograph.rst
  doc/dev/sharp_bits.rst
  doc/releases/changelog-0.9.0.md
  frontend/catalyst/jit.py
  frontend/catalyst/passes.py
  mlir/README.rst
Labels: urgent

#1258 Daily rc sync to main
  doc/dev/autograph.rst
  doc/dev/devices.rst
  doc/dev/quick_start.rst
  doc/dev/sharp_bits.rst
  doc/releases/changelog-0.9.0.md
  frontend/catalyst/jit.py
  frontend/catalyst/passes.py
  frontend/catalyst/tracing/type_signatures.py
  frontend/test/conftest.py
  frontend/test/pytest/test_global_phase.py
  frontend/test/pytest/test_jax_dynamic_api.py
  frontend/test/pytest/test_mid_circuit_measurement.py
  frontend/test/pytest/test_seeded_qjit.py
  mlir/README.rst
  mlir/lib/Driver/CompilerDriver.cpp
  mlir/lib/Driver/Pipelines.cpp
  mlir/test/CMakeLists.txt
  mlir/test/cli/DumpPipeline.mlir
  runtime/Makefile
  runtime/README.rst
Labels: urgent
