Repository PennyLaneAI/catalyst, pull requests merged in 2024-07, with the labels that each got.

#891 Bump Catalyst RC version from 0.6 to 0.7
  .github/workflows/check-pl-compat.yaml
Labels: CI

#892 Bump Catalyst RC version from 0.6 to 0.7 (#891)
  .github/workflows/check-pl-compat.yaml
Labels: CI

#893 Pin OQC client to version less than 3.6.0
  .github/workflows/build-wheel-macos-arm64.yaml
  frontend/catalyst/third_party/oqc/oqc_device.py
Labels: ci:build-wheels

#890 [Frontend] Support capturing dynamically-shaped arrays from outer sco…
  doc/changelog.md
  frontend/catalyst/api_extensions/control_flow.py
  frontend/catalyst/compiler.py
  frontend/catalyst/jax_extras/__init__.py
  frontend/catalyst/jax_extras/tracing.py
  frontend/catalyst/jax_primitives.py
  frontend/catalyst/jax_tracer.py
  frontend/test/pytest/test_jax_dynamic_api.py
Labels: frontend, ci:build-wheels

#921 [CI] Automatically release nightly Catalyst builds on TestPyPI
  .github/workflows/build-nightly-release.yaml
  .github/workflows/build-wheel-linux-arm64.yaml
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/set_nightly_version.py
  frontend/catalyst/_version.py
Labels: CI

#835 Autograph works when applied to a function decorated with vmap
  doc/changelog.md
  frontend/catalyst/autograph/ag_primitives.py
  frontend/catalyst/autograph/transformer.py
  frontend/test/pytest/test_autograph.py
Labels: good first issue, frontend

#934 [CI] Fix GH action race condition and demo tests
  .github/workflows/build-nightly-release.yaml
  .github/workflows/check-catalyst.yaml
  .github/workflows/check-formatting.yaml
  .github/workflows/check-pl-compat.yaml
  requirements.txt
Labels: CI

#942 Add tests for qjit applied to a function decorated with for_loop or while_loop
  doc/changelog.md
  frontend/test/pytest/test_autograph.py
Labels: frontend

#941 [CI] Reduce # of configurations for nightly releases on TestPyPI
  .github/workflows/build-nightly-release.yaml
Labels: CI

#947 Add missing backtick
  doc/changelog.md
Labels: documentation

#944 Support for some non-boolean types as predicates of a conditional with Autograph
  doc/changelog.md
  frontend/catalyst/api_extensions/control_flow.py
  frontend/test/pytest/test_conditionals.py
Labels: bug, frontend

#943 Add step-by-step tutorial for adding a new dialect
  doc/dev/dialects.rst
  doc/dev/transforms.rst
  doc/index.rst
Labels: docs

#954 [NFC] Correct module description at __init__.py
  frontend/catalyst/api_extensions/__init__.py
Labels: documentation

#936 Add seeded execution to the Catalyst runtime
  doc/changelog.md
  frontend/catalyst/compiler.py
  frontend/catalyst/jit.py
  frontend/catalyst/utils/gen_mlir.py
  frontend/test/pytest/test_mid_circuit_measurement.py
  frontend/test/pytest/test_seeded_qjit.py
  mlir/lib/Quantum/Transforms/ConversionPatterns.cpp
  mlir/test/Quantum/ConversionTest.mlir
  runtime/examples/grad_qfunc.ll
  runtime/examples/probs_qfunc.ll
  runtime/examples/state_qfunc.ll
  runtime/include/QuantumDevice.hpp
  runtime/include/RuntimeCAPI.h
  runtime/lib/backend/common/Utils.hpp
  runtime/lib/backend/lightning/lightning_dynamic/LightningSimulator.cpp
  runtime/lib/backend/lightning/lightning_dynamic/LightningSimulator.hpp
  runtime/lib/backend/lightning/lightning_kokkos/LightningKokkosSimulator.cpp
  runtime/lib/backend/lightning/lightning_kokkos/LightningKokkosSimulator.hpp
  runtime/lib/capi/ExecutionContext.hpp
  runtime/lib/capi/RuntimeCAPI.cpp
  runtime/tests/Test_CacheManager.cpp
  runtime/tests/Test_DLManager.cpp
  runtime/tests/Test_LightningCoreQIS.cpp
  runtime/tests/Test_LightningGateSet.cpp
  runtime/tests/Test_LightningGradient.cpp
  runtime/tests/Test_LightningMeasures.cpp
  runtime/tests/Test_OpenQasmDevice.cpp
Labels: reviewer:require-wheels, author:build-wheels

#961 [CI] Fix author:build-wheels
  .github/workflows/check-for-wheel-build.yml
Labels: author:build-wheels

#965 Fix issue with dependency bump script
  .github/workflows/set_dep_versions.py
Labels: CI

#978 Change EnzymeStatic-18 to -19 in all github build scripts
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/scripts/linux_arm64/rh8/build_enzyme.sh
Labels: reviewer:require-wheels, author:build-wheels

#967 Pass instrumentation console test when NVIDIA GPU is detected
  frontend/test/lit/test_instrumentation_console.py
Labels: housecleaning

#966 Add devices page to the documentation
  doc/changelog.md
  doc/dev/devices.rst
  doc/dev/quick_start.rst
  doc/index.rst
  frontend/catalyst/jit.py
Labels: docs

#977 Add missing patch to wheel scripts
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/scripts/linux_arm64/rh8/build_llvm.sh
  .github/workflows/scripts/linux_arm64/rh8/build_mhlo.sh
  frontend/test/async_tests/test_async.py
Labels: reviewer:require-wheels, author:build-wheels
