Repository PennyLaneAI/catalyst, pull requests merged in 2024-12, with the labels that each got.

#451 Add Hermitian Support for Finite-Shot Measurement Statistics
  .dep-versions
  .github/workflows/build-wheel-macos-arm64.yaml
  doc/releases/changelog-dev.md
  doc/requirements.txt
  frontend/catalyst/compiler.py
  frontend/test/pytest/test_measurements_shots_results.py
  runtime/README.rst
Labels: runtime, frontend

#1357 Create stable ABI wheels for Python 3.12 and up
  doc/releases/changelog-dev.md
  setup.py
Labels: author:build-wheels

#1348 Add first draft of OQD trapped-ion device TOML databases and APIs
  MANIFEST.in
  Makefile
  doc/releases/changelog-dev.md
  frontend/catalyst/third_party/oqd/__init__.py
  frontend/catalyst/third_party/oqd/oqd_database_managers.py
  frontend/catalyst/third_party/oqd/src/oqd_beam_parameters.toml
  frontend/catalyst/third_party/oqd/src/oqd_device_parameters.toml
  frontend/catalyst/third_party/oqd/src/oqd_qubit_parameters.toml
  frontend/catalyst/utils/toml_utils.py
  frontend/test/pytest/test_toml_utils.py
  frontend/test/test_oqd/oqd/oqd_beam_parameters.toml
  frontend/test/test_oqd/oqd/oqd_qubit_parameters.toml
  frontend/test/test_oqd/oqd/test_oqd_database_managers.py
Labels: reviewer:require-wheels, author:build-wheels

#1359 Update lightning version for dynamic device shots
  .dep-versions
  doc/requirements.txt
Labels: do-not-merge

#1363 Retire the Dev Containers for Catalyst
  .devcontainer/Dockerfile
  .devcontainer/dev/Dockerfile
  .devcontainer/dev/devcontainer.json
  .devcontainer/dev/post-install.sh
  .devcontainer/devcontainer.json
  README.md
  doc/dev/installation.rst
Labels: housecleaning

#1366 Clean the Standalone Plugin when needed
  Makefile
Labels: author:build-wheels

#1355 Add OQD device default backend
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/check-catalyst.yaml
  .github/workflows/constants.yaml
  .github/workflows/scripts/linux_arm64/rh8/build_catalyst.sh
  .github/workflows/scripts/linux_arm64/rh8/test_wheels.sh
  Makefile
  doc/dev/devices.rst
  doc/releases/changelog-dev.md
  frontend/catalyst/third_party/oqd/__init__.py
  frontend/catalyst/third_party/oqd/oqd_device.py
  frontend/catalyst/third_party/oqd/src/CMakeLists.txt
  frontend/catalyst/third_party/oqd/src/Makefile
  frontend/catalyst/third_party/oqd/src/OQDDevice.cpp
  frontend/catalyst/third_party/oqd/src/OQDDevice.hpp
  frontend/catalyst/third_party/oqd/src/OQDRunner.hpp
  frontend/catalyst/third_party/oqd/src/oqd.toml
  frontend/catalyst/third_party/oqd/src/tests/CMakeLists.txt
  frontend/catalyst/third_party/oqd/src/tests/Test_OQDDevice.cpp
  frontend/catalyst/third_party/oqd/src/tests/runner_main.cpp
  frontend/catalyst/utils/runtime_environment.py
  frontend/test/test_oqd/conftest.py
  frontend/test/test_oqd/oqd/test_oqd_device.py
  setup.py
Labels: author:build-wheels, urgent

#1375 Minor fixes to standalone plugin and makefile
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/check-catalyst.yaml
  .github/workflows/scripts/linux_arm64/rh8/build_catalyst.sh
  Makefile
  frontend/catalyst/example_entry_point/__init__.py
  frontend/test/pytest/test_mlir_plugin.py
  mlir/Makefile
Labels: author:build-wheels

#1371 Add make option to enable pip install verbose output
  Makefile
Labels: urgent

#1377 Fix latest/latest/latest failure
  .github/workflows/check-pl-compat.yaml
  Makefile
Labels: urgent

#1367 Reduce max-parallel to 1 for Linux Arm 64 workflow
  .github/workflows/build-wheel-linux-arm64.yaml
Labels: author:build-wheels

#1370 Build wheels for the standalone plugin
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/scripts/linux_arm64/rh8/build_catalyst.sh
  Makefile
  doc/releases/changelog-dev.md
  frontend/catalyst/example_entry_point/__init__.py
  setup.py
  standalone_plugin_wheel/MANIFEST.in
  standalone_plugin_wheel/setup.py
  standalone_plugin_wheel/standalone_plugin/__init__.py
  standalone_plugin_wheel/standalone_plugin/test/test_mlir_plugin.py
Labels: author:build-wheels

#1380 Add runtime coverage support on macOS
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/check-catalyst.yaml
  .github/workflows/scripts/linux_arm64/rh8/build_catalyst.sh
  frontend/catalyst/third_party/oqc/src/CMakeLists.txt
  frontend/catalyst/third_party/oqc/src/Makefile
  frontend/catalyst/third_party/oqc/src/tests/CMakeLists.txt
  frontend/catalyst/third_party/oqd/src/CMakeLists.txt
  frontend/catalyst/third_party/oqd/src/Makefile
  frontend/catalyst/third_party/oqd/src/tests/CMakeLists.txt
  frontend/catalyst/utils/CMakeLists.txt
  runtime/.gitignore
  runtime/CMakeLists.txt
  runtime/Makefile
  runtime/lib/backend/openqasm/CMakeLists.txt
  runtime/lib/capi/CMakeLists.txt
  runtime/lib/registry/CMakeLists.txt
  runtime/tests/CMakeLists.txt
  setup.py
Labels: reviewer:require-wheels, author:build-wheels

#1385 Pass the Py_LIMITED_API macro to Extensions
  doc/releases/changelog-dev.md
  setup.py
Labels: reviewer:require-wheels, author:build-wheels, urgent

#1180 [MLIR] Provide convenience gate builders in tablegen
  mlir/include/Quantum/IR/QuantumOps.td
Labels: enhancement

#1390 Skip oqd pytests in build-wheels
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/scripts/linux_arm64/rh8/test_wheels.sh
  Makefile
  frontend/test/test_oqd/conftest.py
  frontend/test/test_oqd/oqd/oqd_beam_parameters.toml
  frontend/test/test_oqd/oqd/oqd_qubit_parameters.toml
  frontend/test/test_oqd/oqd/test_oqd_database_managers.py
  frontend/test/test_oqd/oqd/test_oqd_device.py
Labels: reviewer:require-wheels, author:build-wheels, urgent

#1386 Revert openblas linking changes from #451
  .dep-versions
  .github/workflows/build-wheel-macos-arm64.yaml
  doc/requirements.txt
  frontend/catalyst/compiler.py
Labels: bug

#1391 Replace pybind11 with nanobind in the OQC module
  Makefile
  doc/releases/changelog-dev.md
  frontend/catalyst/third_party/oqc/src/CMakeLists.txt
  frontend/catalyst/third_party/oqc/src/oqc_python_module.cpp
  frontend/catalyst/third_party/oqc/src/tests/CMakeLists.txt
  frontend/catalyst/utils/CMakeLists.txt
  runtime/CMakeLists.txt
  runtime/lib/backend/openqasm/CMakeLists.txt
Labels: author:build-wheels

#1154 Create a finite state machine analysis pass to propagate Pauli basis states, and use it to disentangle CNOTs and SWAPs
  doc/releases/changelog-dev.md
  mlir/include/Quantum/Transforms/Passes.h
  mlir/include/Quantum/Transforms/Passes.td
  mlir/lib/Catalyst/Transforms/RegisterAllPasses.cpp
  mlir/lib/Quantum/Transforms/CMakeLists.txt
  mlir/lib/Quantum/Transforms/DisentangleCNOT.cpp
  mlir/lib/Quantum/Transforms/DisentangleSWAP.cpp
  mlir/lib/Quantum/Transforms/PropagateSimpleStatesAnalysis.hpp
  mlir/test/Quantum/DisentangleCNOTTest.mlir
  mlir/test/Quantum/DisentangleSWAPTest.mlir
  mlir/test/Quantum/PropagateSimpleStatesTest.mlir
Labels: enhancement
