Repository PennyLaneAI/catalyst, pull requests merged in 2024-09, with the labels that each got.

#1089 Bump PennyLane and Lightning minimum versions
  .dep-versions
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/check-catalyst.yaml
  .github/workflows/check-pl-compat.yaml
  .github/workflows/scripts/linux_arm64/rh8/build_catalyst.sh
  .github/workflows/scripts/linux_arm64/rh8/test_wheels.sh
  Makefile
  doc/requirements.txt
  frontend/test/pytest/test_adjoint.py
  runtime/Makefile
  setup.py
Labels: urgent

#1104 Move minimum Python version from 3.9 to 3.10
  .github/workflows/build-wheel-linux-arm64.yaml
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/constants.yaml
  README.md
  doc/dev/installation.rst
  setup.py
Labels: reviewer:require-wheels, author:build-wheels

#1117 [tests] Explicitly pass `ExecutionConfig` to qjit device in `test_qjit_device`
  frontend/test/pytest/test_device_api.py
Labels: author:build-wheels

#1097 Add full support for JAX linear algebra functions invoked from within a `qjit` block
  doc/dev/jax_integration.rst
  doc/releases/changelog-dev.md
  frontend/catalyst/jax_extras/jax_scipy_linalg_warnings.py
  frontend/catalyst/jit.py
  frontend/catalyst/utils/jax_cpu_lapack_kernels/lapack_kernels.cpp
  frontend/catalyst/utils/jax_cpu_lapack_kernels/lapack_kernels.hpp
  frontend/catalyst/utils/jax_cpu_lapack_kernels/lapack_kernels_using_lapack.cpp
  frontend/catalyst/utils/libcustom_calls.cpp
  frontend/test/pytest/test_jax_linalg.py
  frontend/test/pytest/test_jax_linalg_in_circuit.py
  frontend/test/pytest/test_jax_numerical.py
  setup.py
Labels: author:build-wheels

#1121 Skip a test for local folding with exponential extrapolate
  frontend/test/pytest/test_mitigation.py
Labels: author:build-wheels

#1125 [docs] Removing `pip install` output dump in demo
  demos/adaptive_circuits_demo.ipynb
Labels: documentation

#1122 Add "Known Issues" section to the installation guide
  doc/dev/installation.rst
  doc/releases/changelog-dev.md
Labels: documentation

#1138 Remove old QJITDevice class and references
  doc/dev/custom_devices.rst
  doc/releases/changelog-dev.md
  frontend/catalyst/device/__init__.py
  frontend/catalyst/device/qjit_device.py
  frontend/catalyst/qfunc.py
  frontend/test/pytest/test_config_functions.py
  frontend/test/pytest/test_device_api.py
  frontend/test/pytest/test_measurement_transforms.py
  frontend/test/pytest/test_qnode.py
Labels: frontend

#1141 Move capability loading to QJITDevice constructor
  doc/releases/changelog-dev.md
  frontend/catalyst/device/qjit_device.py
  frontend/catalyst/qfunc.py
  frontend/catalyst/third_party/cuda/catalyst_to_cuda_interpreter.py
  frontend/test/pytest/test_config_functions.py
  frontend/test/pytest/test_device_api.py
  frontend/test/pytest/test_measurement_transforms.py
Labels: frontend

#1149 Refactor device code around capabilities [NFC]
  doc/releases/changelog-dev.md
  frontend/catalyst/device/decomposition.py
  frontend/catalyst/device/qjit_device.py
  frontend/catalyst/device/verification.py
  frontend/catalyst/from_plxpr.py
  frontend/catalyst/utils/toml.py
  frontend/test/lit/test_decomposition.py
  frontend/test/lit/test_quantum_control.py
  frontend/test/pytest/device/test_decomposition.py
  frontend/test/pytest/test_config_functions.py
  frontend/test/pytest/test_device_api.py
  frontend/test/pytest/test_measurement_transforms.py
  frontend/test/pytest/test_preprocess.py
  frontend/test/pytest/test_verification.py
Labels: frontend

#1150 Fix batch size calculation with vmap and static_argnums
  doc/releases/changelog-dev.md
  frontend/catalyst/api_extensions/function_maps.py
  frontend/test/pytest/test_vmap.py
Labels: bug, frontend

#1151 Use inspect module to get argument counts
  doc/releases/changelog-dev.md
  frontend/catalyst/api_extensions/control_flow.py
  frontend/test/pytest/test_conditionals.py
Labels: bug, frontend

#645 Remove 'puts' error message from async lowering
  doc/releases/changelog-dev.md
  mlir/include/Catalyst/Transforms/AsyncUtils.h
  mlir/lib/Catalyst/Transforms/AsyncUtils.cpp
  mlir/lib/Catalyst/Transforms/DetectQNodes.cpp
  mlir/test/Catalyst/AsyncException3.mlir
Labels: compiler, housecleaning
