Repository PennyLaneAI/catalyst, pull requests merged in 2025-08, with the labels that each got.

#1955 Issue 1220 add merge rotation patterns for qml rot and qml crot
  doc/releases/changelog-dev.md
  frontend/catalyst/passes/builtin_passes.py
  mlir/include/Quantum/Transforms/Passes.td
  mlir/lib/Quantum/Transforms/MergeRotationsPatterns.cpp
  mlir/lib/Quantum/Transforms/merge_rotation.cpp
  mlir/test/Quantum/MergeRotationsTest.mlir
Labels: external

#1981 [BUG] Fix measure from sample shot vector condition
  doc/releases/changelog-dev.md
  frontend/catalyst/device/decomposition.py
  frontend/test/pytest/test_measurement_transforms.py
Labels: bug

#1952 Replacing `device(..., shots=...)` with `set_shots`
  .dep-versions
  doc/releases/changelog-dev.md
  doc/requirements.txt
  frontend/catalyst/device/qjit_device.py
  frontend/catalyst/device/verification.py
  frontend/catalyst/from_plxpr/from_plxpr.py
  frontend/catalyst/jax_tracer.py
  frontend/catalyst/qfunc.py
  frontend/test/lit/test_mitigation.py
  frontend/test/pytest/device/test_decomposition.py
  frontend/test/pytest/from_plxpr/test_capture_integration.py
  frontend/test/pytest/from_plxpr/test_from_plxpr.py
  frontend/test/pytest/test_adjoint.py
  frontend/test/pytest/test_autograph.py
  frontend/test/pytest/test_automatic_qubit_management.py
  frontend/test/pytest/test_cuda_integration.py
  frontend/test/pytest/test_custom_devices.py
  frontend/test/pytest/test_device_api.py
  frontend/test/pytest/test_jit_behaviour.py
  frontend/test/pytest/test_measurement_dynamic_shapes.py
  frontend/test/pytest/test_measurement_transforms.py
  frontend/test/pytest/test_measurements_results.py
  frontend/test/pytest/test_measurements_shots_results.py
  frontend/test/pytest/test_mid_circuit_measurement.py
  frontend/test/pytest/test_mitigation.py
  frontend/test/pytest/test_pytree_args.py
  frontend/test/pytest/test_seeded_qjit.py
  frontend/test/pytest/test_shotvector.py
  frontend/test/pytest/test_snapshot.py
  frontend/test/pytest/test_template.py
  frontend/test/pytest/test_transform.py
  frontend/test/pytest/test_variable_wires.py
  frontend/test/pytest/test_verification.py
Labels: frontend

#1986 Pin mac wheels CI runner to MacOS 14
  .github/workflows/build-wheel-macos-arm64.yaml
Labels: reviewer:require-wheels, author:build-wheels

#1990 Fix typos in Gradient and Quantum dialect docs
  mlir/include/Gradient/IR/GradientOps.td
  mlir/include/Quantum/IR/QuantumOps.td
Labels: housecleaning

#2007 On-board catalyst to using new large runner
  .github/workflows/determine-workflow-runner.yml
Labels: urgent
