Repository PennyLaneAI/catalyst, pull requests merged in 2025-01, with the labels that each got.

#1401 Increase minimum plugin version for building linux wheels
  .github/workflows/build-wheel-linux-x86_64.yaml
Labels: author:build-wheels

#1403 Exclude OQD packages, modules and data from wheels
  MANIFEST.in
  Makefile
  doc/dev/devices.rst
  doc/releases/changelog-dev.md
  setup.py
Labels: author:build-wheels, urgent

#1408 Allow quantum registers returned from functions during buffer deallocation
  .github/workflows/build-enzyme-v0.0.130.yaml
  .github/workflows/build-wheel-linux-arm64.yaml
  .github/workflows/build-wheel-linux-x86_64.yaml
  .github/workflows/build-wheel-macos-arm64.yaml
  .github/workflows/build-wheel-macos-x86_64.yaml
  .github/workflows/scripts/linux_arm64/rh8/build_catalyst.sh
  .github/workflows/scripts/linux_arm64/rh8/build_lld.sh
  .github/workflows/scripts/linux_arm64/rh8/build_llvm.sh
  .github/workflows/scripts/linux_arm64/rh8/test_wheels.sh
  mlir/Makefile
  mlir/patches/mlir-buffer-deallocation.patch
Labels: bug, upstream

#1427 Remove Python OQD Database Managers module
  frontend/catalyst/third_party/oqd/__init__.py
  frontend/catalyst/third_party/oqd/oqd_database_managers.py
  frontend/catalyst/utils/toml_utils.py
  frontend/test/pytest/test_toml_utils.py
Labels: urgent

#1444 Fix macos failure due to test schedule
  .github/workflows/build-wheel-macos-arm64.yaml
Labels: author:build-wheels

#1469 Fixed Z gate name matching in Ion decomposition pass
  mlir/lib/Quantum/Transforms/IonsDecompositionPatterns.cpp
Labels: bug, compiler, OQD

#1473 Fix pulse target qubit in MS gate lowering
  mlir/lib/Ion/IR/IonOps.cpp
  mlir/test/Ion/QuantumToIon.mlir
Labels: OQD

#1474 Fix some typos in 'tracing.py' doc strings
  frontend/catalyst/jax_extras/tracing.py
Labels: documentation

#1471 Optimized Ion Dialect to minimize redundant code in IonOp
  doc/releases/changelog-dev.md
  mlir/include/Ion/IR/IonOps.td
  mlir/include/Ion/Transforms/oqd_database_managers.hpp
  mlir/include/Ion/Transforms/oqd_database_types.hpp
  mlir/lib/Ion/Transforms/quantum_to_ion.cpp
  mlir/test/Ion/Dialect.mlir
  mlir/test/Ion/QuantumToIon.mlir
  mlir/test/Ion/oqd_qubit_parameters.toml
Labels: OQD

#1475 Ensure an `ion.yield` operation is returning a region output to all parallal protocol ops
  doc/releases/changelog-dev.md
  mlir/lib/Ion/IR/IonOps.cpp
  mlir/lib/Ion/Transforms/QuantumToIonPatterns.cpp
  mlir/test/Ion/QuantumToIon.mlir
Labels: OQD

#1480 Update deprecated `gradient_kwargs` usage
  .dep-versions
  doc/releases/changelog-dev.md
  doc/requirements.txt
  frontend/test/pytest/test_gradient.py
Labels: review ready
