Repository PennyLaneAI/catalyst, pull requests merged in 2025-07, with the labels that each got.

#1903 add Hermitian observable support to `from_plxpr`
  doc/releases/changelog-dev.md
  frontend/catalyst/from_plxpr/from_plxpr.py
  frontend/test/pytest/conftest.py
  frontend/test/pytest/test_from_plxpr.py
  frontend/test/pytest/test_measurements_results.py
  frontend/test/pytest/test_measurements_shots_results.py
Labels: review ready

#1923 Fix Python version in mac cache keys
  .github/workflows/build-wheel-macos-arm64.yaml
Labels: CI

#1950 Ensure canonical usage of the qjit decorator
  demos/magic_distillation_demo.ipynb
  frontend/catalyst/api_extensions/control_flow.py
  frontend/test/async_tests/test_async.py
  frontend/test/lit/test_peephole_optimizations.py
  frontend/test/pytest/from_plxpr/test_capture_integration.py
  frontend/test/pytest/test_adjoint.py
  frontend/test/pytest/test_assertion.py
  frontend/test/pytest/test_braket_local_devices.py
  frontend/test/pytest/test_braket_remote_devices.py
  frontend/test/pytest/test_buffer_args.py
  frontend/test/pytest/test_conditionals.py
  frontend/test/pytest/test_contexts.py
  frontend/test/pytest/test_gradient.py
  frontend/test/pytest/test_jax_dynamic_api.py
  frontend/test/pytest/test_jnp_vs_np.py
  frontend/test/pytest/test_keyword_arguments.py
  frontend/test/pytest/test_loops.py
  frontend/test/pytest/test_operations.py
  frontend/test/pytest/test_peephole_optimizations.py
  frontend/test/pytest/test_qnode.py
  frontend/test/pytest/test_quantum_control.py
  frontend/test/pytest/test_unsupported_argument_type.py
  frontend/test/pytest/test_variable_wires.py
Labels: housecleaning
