Repository PennyLaneAI/catalyst, pull requests merged in 2025-05, with the labels that each got.

#1680 Document the semantics of the QuantumDevice interface
  .dep-versions
  Makefile
  doc/dev/custom_devices.rst
  doc/releases/changelog-dev.md
  doc/requirements.txt
  frontend/catalyst/device/qjit_device.py
  frontend/catalyst/third_party/oqc/src/OQCDevice.cpp
  frontend/catalyst/third_party/oqc/src/OQCDevice.hpp
  frontend/catalyst/third_party/oqc/src/OQCRunner.hpp
  frontend/catalyst/third_party/oqc/src/tests/Test_OQCDevice.cpp
  frontend/test/lit/test_device_api.py
  frontend/test/pytest/test_capture_integration.py
  runtime/include/QuantumDevice.hpp
  runtime/lib/backend/common/Utils.hpp
  runtime/lib/backend/null_qubit/NullQubit.hpp
  runtime/lib/backend/openqasm/OpenQasmDevice.cpp
  runtime/lib/backend/openqasm/OpenQasmDevice.hpp
  runtime/lib/backend/oqd/OQDDevice.cpp
  runtime/lib/backend/oqd/OQDDevice.hpp
  runtime/lib/backend/oqd/OQDRunner.hpp
  runtime/lib/capi/RuntimeCAPI.cpp
  runtime/tests/Test_NullQubit.cpp
  runtime/tests/Test_OQDDevice.cpp
  runtime/tests/Test_OpenQasmDevice.cpp
Labels: runtime

#1710 Fix failing wheels due to missing mbqc dialect module
  Makefile
  doc/releases/changelog-dev.md
Labels: author:build-wheels

#1720 Use explicit device_release primitive in the frontend
  Makefile
  doc/dev/sharp_bits.rst
  doc/releases/changelog-dev.md
  frontend/catalyst/api_extensions/quantum_operators.py
  frontend/catalyst/from_plxpr.py
  frontend/catalyst/jax_primitives.py
  frontend/catalyst/jax_tracer.py
  frontend/catalyst/third_party/cuda/catalyst_to_cuda_interpreter.py
  frontend/test/lit/test_split_multiple_tapes.py
Labels: frontend

#1730 Reduce TestPyPI storage load
  .github/workflows/build-nightly-release.yaml
  frontend/catalyst/_version.py
Labels: CI

#1718 Replace Catalyst logo+title header image
  README.md
  doc/_static/pl-catalyst-logo-darkmode.png
  doc/_static/pl-catalyst-logo-lightmode.png
  doc/index.rst
  doc/releases/changelog-dev.md
Labels: documentation, docs

#1687 Fix `get_cmain` for boolean function results
  doc/dev/debugging.rst
  doc/releases/changelog-dev.md
  frontend/catalyst/utils/c_template.py
  frontend/test/pytest/test_c_template.py
  frontend/test/pytest/test_debug.py
Labels: bug, frontend

#1719 Add the compiler option for limiting the Pauli size in PPM's passes
  doc/releases/changelog-dev.md
  frontend/catalyst/passes/builtin_passes.py
  frontend/test/pytest/test_peephole_optimizations.py
  mlir/include/QEC/Transforms/Passes.td
  mlir/include/QEC/Transforms/Patterns.h
  mlir/include/QEC/Utils/PauliStringWrapper.h
  mlir/lib/QEC/Transforms/CommuteCliffordPastPPM.cpp
  mlir/lib/QEC/Transforms/CommuteCliffordTPPR.cpp
  mlir/lib/QEC/Transforms/commute_clifford_past_ppm.cpp
  mlir/lib/QEC/Transforms/commute_clifford_t_ppr.cpp
  mlir/lib/QEC/Utils/PauliStringWrapper.cpp
  mlir/test/QEC/CommuteCliffordPastPPMTest.mlir
  mlir/test/QEC/CommuteCliffordTPPRTest.mlir
Labels: enhancement

#1664 Implement a decomposition of PPRs into PPMs
  doc/releases/changelog-dev.md
  frontend/catalyst/passes/__init__.py
  frontend/catalyst/passes/builtin_passes.py
  frontend/catalyst/passes/pass_api.py
  frontend/test/pytest/test_peephole_optimizations.py
  mlir/include/QEC/IR/CMakeLists.txt
  mlir/include/QEC/IR/QECDialect.h
  mlir/include/QEC/IR/QECDialect.td
  mlir/include/QEC/Transforms/CMakeLists.txt
  mlir/include/QEC/Transforms/PPRDecomposeUtils.h
  mlir/include/QEC/Transforms/Passes.h
  mlir/include/QEC/Transforms/Passes.td
  mlir/include/QEC/Transforms/Patterns.h
  mlir/include/QEC/Utils/PauliStringWrapper.h
  mlir/include/Quantum/IR/QuantumOps.td
  mlir/lib/Catalyst/Transforms/RegisterAllPasses.cpp
  mlir/lib/QEC/IR/CMakeLists.txt
  mlir/lib/QEC/IR/QECDialect.cpp
  mlir/lib/QEC/Transforms/CMakeLists.txt
  mlir/lib/QEC/Transforms/DecomposeCliffordPPR.cpp
  mlir/lib/QEC/Transforms/DecomposeNonCliffordPPR.cpp
  mlir/lib/QEC/Transforms/PPRDecomposeUtils.cpp
  mlir/lib/QEC/Transforms/decompose_clifford_ppr.cpp
  mlir/lib/QEC/Transforms/decompose_non_clifford_ppr.cpp
  mlir/lib/QEC/Utils/PauliStringWrapper.cpp
  mlir/test/QEC/DecomposeCliffordPPR.mlir
  mlir/test/QEC/DecomposeNonCliffordPPR.mlir
  mlir/test/QEC/SmokeTest.mlir
Labels: enhancement

#1733 📦️ Export Headers for the MLIRQuantum Dialect in the Wheel
  .gitignore
  MANIFEST.in
  Makefile
  frontend/catalyst/utils/runtime_environment.py
  frontend/test/pytest/test_utils_runtime_environment.py
  mlir/cmake/modules/CMakeLists.txt
Labels: reviewer:require-wheels, author:build-wheels, external

#1761 Reapply "Add call to python compiler (#1715)" (#1760)
  .dep-versions
  doc/releases/changelog-dev.md
  doc/requirements.txt
  frontend/catalyst/compiler.py
Labels: author:build-wheels
