Repository PennyLaneAI/catalyst, pull requests merged in 2025-06, with the labels that each got.

#1763 Add more OQD tests
  doc/releases/changelog-dev.md
  frontend/catalyst/third_party/oqd/oqd_device.py
  frontend/test/test_oqd/oqd/conftest.py
  frontend/test/test_oqd/oqd/test_openapl_generation.py
  frontend/test/test_oqd/oqd/test_oqd_device.py
  runtime/include/OQDRuntimeCAPI.h
  runtime/lib/OQDcapi/OQDRuntimeCAPI.cpp
  runtime/lib/backend/oqd/OQDDevice.hpp
  runtime/lib/backend/oqd/oqd.toml
  runtime/tests/Test_OQDDevice.cpp
Labels: OQD

#1803 Move json and toml cmake `fetchcontent`s to root mlir directory
  mlir/CMakeLists.txt
  mlir/lib/Ion/Transforms/CMakeLists.txt
  mlir/lib/QEC/Transforms/CMakeLists.txt
Labels: do-not-merge

#1814 use `dataclass.replace` to update `ExecutionConfig` or `MCMConfig`
  doc/releases/changelog-dev.md
  frontend/catalyst/jax_tracer.py
  frontend/catalyst/qfunc.py
  frontend/test/pytest/test_gradient.py
Labels: review ready
